#pragma once
#include <iostream>
#include <string>
#include <iomanip>
#include <algorithm>
#include <random>
#include <fstream>
#include <sstream>
#include <exception>
#include <chrono>
using std::cout;
using std::endl;
using std::cin;
using std::string;
using std::setw;
using std::setfill;
using std::getline;
using std::ifstream;
using std::istringstream;
